#if !NO_CUTURE_ASPNETCORE_ACTIONAUDITING_GENERATOR_ATTRIBUTE

// <Auto-Generated/>

#pragma warning disable IDE0005
#pragma warning disable IDE0130
#pragma warning disable CS9113

namespace System.Resources;

/// <summary>
/// 标记类型需要生成常量
/// </summary>
/// <param name="ParseMode">常量值转换类型</param>
/// <param name="Separator">层级分隔符</param>
/// <param name="ConstantSuffix">常量名称后缀</param>
/// <param name="ConstantValuePrefix">常量值前缀</param>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class GeneratedConstantsAttribute(ConstantValueParseMode ParseMode = ConstantValueParseMode.Default,
                                                  string? Separator = ":",
                                                  string ConstantSuffix = "Constant",
                                                  string? ConstantValuePrefix = null)
    : Attribute
{
}

/// <summary>
/// 常量值转换模式
/// </summary>
internal enum ConstantValueParseMode
{
    /// <summary>
    /// 默认
    /// </summary>
    Default,

    /// <summary>
    /// 小写
    /// </summary>
    LowerCase,

    /// <summary>
    /// 大写
    /// </summary>
    UpperCase,

    /// <summary>
    /// 蛇形命名
    /// </summary>
    SnakeCase,

    /// <summary>
    /// 常量大写
    /// </summary>
    ConstantCase,

    /// <summary>
    /// 短横线命名
    /// </summary>
    KebabCase,
}

#endif
